name: CI

on: [push, pull_request]

jobs:
    ci:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                include:
                    - rye_version: "0.32.0"
                      rye_home: "/opt/rye"
                      use_uv: "true"

        steps:
            - uses: actions/checkout@v3

            - name: Check cache for Rye
              uses: actions/cache@v4
              id: get-cache
              with:
                  key: "${{ matrix.rye_version }}-${{ matrix.use_uv }}"
                  path: "${{ matrix.rye_home }}"

            - name: Add Rye to PATH
              run: echo "${{ matrix.rye_home }}/shims" >> $GITHUB_PATH && echo "${{ matrix.rye_home }}/tools" >> $GITHUB_PATH

            - name: Install Rye
              uses: phi-friday/install-rye@v1.2
              if: steps.get-cache.outputs.cache-hit != 'true'
              id: install-rye
              with:
                  rye_version: "${{ matrix.rye_version }}"
                  rye_home: "${{ matrix.rye_home }}"
                  use_uv: "${{ matrix.use_uv }}"

            - name: Cache virtual environment
              uses: actions/cache@v4
              id: venv-cache
              with:
                  key: venv-${{ runner.os }}-${{ hashFiles('requirements.lock') }}
                  path: ".venv"

            - name: Get dependencies
              run: rye sync

            - name: Enter virtual env
              run: . .venv/bin/activate

            - name: Run Ruff formatter/linter
              run: ./.venv/bin/ruff check && ./.venv/bin/ruff format --check

            - name: Check types with MyPy
              uses: sasanquaneuf/mypy-github-action@releases/v1
              with:
                  checkName: "ci"
